/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.73
 * Generated at: 2017-09-13 18:28:39 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.Random;
import java.text.SimpleDateFormat;
import java.text.DateFormat;
import java.util.Date;
import java.sql.*;

public final class feregsuccess_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        ");
       
        DateFormat df = new SimpleDateFormat("yyMM");
        Date dateobj = new Date();
        
        String feid =df.format(dateobj).toString()+request.getParameter("adhar");
        String fname= request.getParameter("fname");
        String mname= request.getParameter("mname");
        String lname = request.getParameter("lname");
        String email= request.getParameter("email");
        String username= request.getParameter("username");
        String passwd= request.getParameter("passwd");
        String passwd2= request.getParameter("passwd2");
        String adhar = request.getParameter("adhar");
        String mobile = request.getParameter("mobile");
        String state= request.getParameter("state");
        String city= request.getParameter("city");
        String pincode = request.getParameter("pin");
        DateFormat df1 = new SimpleDateFormat("yyyy-MM-dd");
        String joindate = df1.format(dateobj).toString();
        String d= (request.getParameter("d"));
        String m= (request.getParameter("m"));
        String y= (request.getParameter("y"));
       String sqlDate= d+"-"+m+"-"+y;
       java.util.Date date = new SimpleDateFormat("MM-dd-yyyy").parse(sqlDate);
        java.sql.Date dob= new java.sql.Date(date.getTime());
        String image= request.getParameter("image");
        String gender= request.getParameter("gender");
        String companyname= request.getParameter("companyname");
       System.out.println(image);
       if(passwd.equals(passwd2))
       {
        Connection con = null;
        PreparedStatement prepStmt = null;
        Statement st=null;
        String frid=null;
         try
            {
        	String sql="select franchisorsID from franchisors where companyname='"+companyname+"' ";
        	Class.forName("com.mysql.jdbc.Driver");
        	con = DriverManager.getConnection("jdbc:mysql://localhost/db","root","xxx");
           st=con.createStatement();
             
             ResultSet rs=st.executeQuery(sql);
             while(rs.next())
             { 
            	 frid=rs.getString(1);
            	           	
             }
             prepStmt = con.prepareStatement("insert into franchisees values(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)");
                    prepStmt.setString(1, feid);
                    prepStmt.setString(2, frid);
                    prepStmt.setString(3, fname);
                     prepStmt.setString(4, mname);
                    prepStmt.setString(5, lname);
                   prepStmt.setString(6, email);
                    prepStmt.setString(7, username);
                     prepStmt.setString(8, passwd);
                     prepStmt.setString(9,adhar);
                     prepStmt.setString(10, mobile);
                    prepStmt.setString(11, state);
                     prepStmt.setString(12, city);
                    prepStmt.setString(13,pincode);
                    prepStmt.setString(14,joindate);
                    prepStmt.setDate(15,dob);
                    prepStmt.setString(16,gender);
                    prepStmt.setString(17,companyname);
                   prepStmt.setString(18,image);
                    int flag = prepStmt.executeUpdate();
                    if (flag > 0) {
                        //session.setAttribute("userid", feid);
                        
      out.write("\r\n");
      out.write("                        <script>\r\n");
      out.write("                        alert(\"Registration Succaeeful !!!\");\r\n");
      out.write("                        window.location = 'login.jsp';\r\n");
      out.write("                        </script>\r\n");
      out.write("                        ");

                        
                       // response.sendRedirect("login.jsp");
                       // out.print("Registration Successfull!"+"<a href='index.jsp'>Go to Login</a>");
                    } else 
                    {
                    	
                        response.sendRedirect("fereg.jsp");
                    }
                    prepStmt.close(); 
                    con.close();
                } catch(Exception e)
                {
           	
      out.write("\r\n");
      out.write("            \t\t<script>\r\n");
      out.write("            \t\talert(\"invalid input\");\r\n");
      out.write("            \t\t\r\n");
      out.write("    \t\t\t\t</script>\r\n");
      out.write("    \t\t\t\t<a href=fereg.jsp> try again</a>\r\n");
      out.write("            \t\t");

            		
            		}
       }else
       {
    	   
      out.write("\r\n");
      out.write("      \t <script type=\"text/javascript\">\r\n");
      out.write("      \talert(\"password not matched !!!\");\r\n");
      out.write("      \twindow.location='frreg.jsp';\r\n");
      out.write("      \t</script>\r\n");
      out.write("      \t    \t");

       }
              
      out.write("\r\n");
      out.write("\r\n");
      out.write("           \t\t\r\n");
      out.write("\r\n");
      out.write("           \t\t");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
