/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.73
 * Generated at: 2017-09-13 18:30:19 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("  \r\n");
      out.write("  <script>\r\n");
      out.write("function startTime() {\r\n");
      out.write("    var today = new Date();\r\n");
      out.write("    var h = today.getHours();\r\n");
      out.write("    var m = today.getMinutes();\r\n");
      out.write("    var s = today.getSeconds();\r\n");
      out.write("    m = checkTime(m);\r\n");
      out.write("    s = checkTime(s);\r\n");
      out.write("    document.getElementById('time').innerHTML =\r\n");
      out.write("    h + \":\" + m + \":\" + s;\r\n");
      out.write("    var t = setTimeout(startTime, 500);\r\n");
      out.write("}\r\n");
      out.write("function checkTime(i) {\r\n");
      out.write("    if (i < 10) {i = \"0\" + i};  // add zero in front of numbers < 10\r\n");
      out.write("    return i;\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("  \r\n");
      out.write("  <title>Easy India</title>\r\n");
      out.write("  <meta charset=\"utf-8\">\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"bootstrap/css/bootstrap.min.css\">\r\n");
      out.write("  <script  src=\"bootstrap/css/bootstrap.min.css\"></script>\r\n");
      out.write("  <script  src=\"js/3.1.1/jquery.min.js\"></script>\r\n");
      out.write("  <script  src=\"bootstrap/js/bootstrap.js\"></script>\r\n");
      out.write("  <script src=\"bootstrap/js/bootstrap.min.js\"></script>\r\n");
      out.write("  <style>\r\n");
      out.write("  body {\r\n");
      out.write("      font: 400 15px Lato, sans-serif;\r\n");
      out.write("      line-height: 1.8;\r\n");
      out.write("      color: #818181;\r\n");
      out.write("      background-color:gray;\r\n");
      out.write("      \r\n");
      out.write("  }\r\n");
      out.write("  p{\r\n");
      out.write("   font-size: 20px;\r\n");
      out.write("   color:white;\r\n");
      out.write("  }\r\n");
      out.write("  h2 {\r\n");
      out.write("      font-size: 30px;\r\n");
      out.write("      text-transform: uppercase;\r\n");
      out.write("      color: red;\r\n");
      out.write("      font-weight: 600;\r\n");
      out.write("      margin-bottom: 30px;\r\n");
      out.write("      font-family: Segoe Print, serif;\r\n");
      out.write("  }\r\n");
      out.write("  h4 {\r\n");
      out.write("      font-size: 19px;\r\n");
      out.write("      line-height: 1.375em;\r\n");
      out.write("      color: white;\r\n");
      out.write("      font-weight: 400;\r\n");
      out.write("      margin-bottom: 30px;\r\n");
      out.write("  }\r\n");
      out.write("   .navbar {\r\n");
      out.write("      margin-bottom:;\r\n");
      out.write("      height: 68px;\r\n");
      out.write("      background-color: #F4A460;\r\n");
      out.write("      border: 0;\r\n");
      out.write("      font-size: 20px !important;\r\n");
      out.write("      \r\n");
      out.write("      letter-spacing: 1px;\r\n");
      out.write("      border-radius: 0;\r\n");
      out.write("      font-family: times new roman, serif;\r\n");
      out.write("  }\r\n");
      out.write("  .navbar li a, .navbar .navbar-brand {\r\n");
      out.write("      color: black !important;\r\n");
      out.write("  }\r\n");
      out.write("  .navbar-nav li a:hover, .navbar-nav li.active a {\r\n");
      out.write("      color: blue !important;\r\n");
      out.write("      background-color: pink !important;\r\n");
      out.write("  }\r\n");
      out.write("  .navbar-default, .navbar-toggle {\r\n");
      out.write("      border-color: transparent;\r\n");
      out.write("      color: #fff !important;\r\n");
      out.write("  }  \r\n");
      out.write("  .jumbotron {\r\n");
      out.write("       margin-top: 20px;\r\n");
      out.write("      \r\n");
      out.write("     <!-- background: url(\"images/fms2.PNG\") no-repeat;-->\r\n");
      out.write("      \r\n");
      out.write("    \r\n");
      out.write("      font-family: Montserrat, sans-serif;\r\n");
      out.write("       width: 100%;\r\n");
      out.write("   \r\n");
      out.write("      \r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write("  .panel {\r\n");
      out.write("   \r\n");
      out.write("      border: 1px solid #f4511e; \r\n");
      out.write("      border-radius:0 !important;\r\n");
      out.write("      transition: box-shadow 0.5s;\r\n");
      out.write("  }\r\n");
      out.write("  .panel:hover {\r\n");
      out.write("      box-shadow: 5px 0px 40px rgba(0,0,0, .2);\r\n");
      out.write("  }\r\n");
      out.write("  .panel-footer .btn:hover {\r\n");
      out.write("      border: 1px solid #f4511e;\r\n");
      out.write("      background-color: #fff !important;\r\n");
      out.write("      color: #f4511e;\r\n");
      out.write("  }\r\n");
      out.write("  .panel-heading {\r\n");
      out.write("      color: #fff !important;\r\n");
      out.write("      background-color: #e43a !important;\r\n");
      out.write("      background: url(\"images/bg3.jpg\") no-repeat 62% 34%;\r\n");
      out.write("      padding: 25px;\r\n");
      out.write("      border-bottom: 1px solid transparent;\r\n");
      out.write("      border-top-left-radius: 0px;\r\n");
      out.write("      border-top-right-radius: 0px;\r\n");
      out.write("      border-bottom-left-radius: 0px;\r\n");
      out.write("      border-bottom-right-radius: 0px;\r\n");
      out.write("  }\r\n");
      out.write("  .panel-footer {\r\n");
      out.write("      background-color: white !important;\r\n");
      out.write("      background: url(\"images/bg3.jpg\") no-repeat 62% 34%;\r\n");
      out.write("  }\r\n");
      out.write("  .panel-footer h3 {\r\n");
      out.write("      font-size: 32px;\r\n");
      out.write("  }\r\n");
      out.write("  .panel-footer h4 {\r\n");
      out.write("      color: #aaa;\r\n");
      out.write("      font-size: 14px;\r\n");
      out.write("  }\r\n");
      out.write("  .panel-footer .btn {\r\n");
      out.write("      margin: 15px 0;\r\n");
      out.write("      background-color: green;\r\n");
      out.write("      color: #fff;\r\n");
      out.write("  }\r\n");
      out.write(" \r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("  }\r\n");
      out.write("  </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body id=\"HomePage\" data-spy=\"scroll\" data-target=\".navbar\" data-offset=\"60\"  onload=\"startTime()\">\r\n");
      out.write("\r\n");
      out.write("<nav class=\"navbar navbar-default navbar-fixed-top\">\r\n");
      out.write("  <div class=\"container\" >\r\n");
      out.write("    <div class=\"navbar-header\">\r\n");
      out.write("      <button type=\"button\" class=\"navbar-toggle\" data-toggle=\"collapse\" data-target=\"#myNavbar\">\r\n");
      out.write("        <span class=\"icon-bar\"></span>\r\n");
      out.write("        <span class=\"icon-bar\"></span>\r\n");
      out.write("        <span class=\"icon-bar\"></span>                        \r\n");
      out.write("      </button>\r\n");
      out.write("      \r\n");
      out.write("      <a href=\"#HomePage\" class=\"navbar-brand\">\r\n");
      out.write("      <img src=\"images/logo.PNG\" alt=\"Franchisee Management System\" title=\"Franchisee Management System\">\r\n");
      out.write("      </a>\r\n");
      out.write("    </div >\r\n");
      out.write("  \r\n");
      out.write("    <div class=\"collapse navbar-collapse\" id=\"myNavbar\"   >\r\n");
      out.write("      <ul class=\"nav navbar-nav navbar-right\">\r\n");
      out.write("     \r\n");
      out.write("       <li><a href=\"#HomePage\" >\r\n");
      out.write("      \t\t<span class=\"glyphicon glyphicon-home\" style=color:white;padding:10px ></span>Home</a></li>\r\n");
      out.write("      <li><a href=\"#Register\">\r\n");
      out.write("            <span class=\"glyphicon glyphicon-user\" style=color:white;padding:10px></span>Register</a></li>\r\n");
      out.write("      <li><a href=\"login.jsp\">\r\n");
      out.write("      \t\t<span class=\"glyphicon glyphicon-log-in\" style=color:white;padding:10px></span>Login</a></li>\r\n");
      out.write("      <li><a href=\"#about\">\r\n");
      out.write("      \t\t<span class=\"glyphicon glyphicon-list-alt\" style=color:white;padding:10px></span>About</a></li>\r\n");
      out.write("      <li><a href=\"#contact\">\r\n");
      out.write("      \t\t<span class=\"glyphicon glyphicon-phone\" style=color:white;padding:10px ></span>Contact</a></li>\r\n");
      out.write("    \r\n");
      out.write("      \t\t<li id=\"time\"></li>\r\n");
      out.write("      </ul>\r\n");
      out.write("   \r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("  </div>\r\n");
      out.write("</nav>\r\n");
      out.write("\r\n");
      out.write("<div class=\"jumbotron \" style=\"padding: 45px 0px 0px 255px;\" >\r\n");
      out.write("<h2><marquee scrollamount=\"9\" width=9% >&lt;&lt;&lt;</marquee>\r\n");
      out.write("<strong>FRANCHISEE MANAGEMENT SYSTEM</strong>\r\n");
      out.write("<marquee scrollamount=\"9\" direction=\"right\" width=9%>&gt;&gt;&gt;</marquee></h2>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"jumbotron \" style=\"margin-top: -35px\" >\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<marquee scrollamount=\"15\" direction=\"up\"  marquee width=24% marquee height=100%>\r\n");
      out.write("\t<img src=\"images/race.jpg\"/>\r\n");
      out.write("\t\r\n");
      out.write("</marquee>\t\r\n");
      out.write("<marquee scrollamount=\"15\" direction=\"left\"  marquee width=25% marquee height=100%>\r\n");
      out.write("\t<img src=\"images/race.jpg\"/>\r\n");
      out.write("\t<img src=\"images/race2.jpg\"/>\r\n");
      out.write("\t<img src=\"images/race3.jpg\"/>\r\n");
      out.write("\t<img src=\"images/race.jpg\"/>\r\n");
      out.write("</marquee>\r\n");
      out.write("<marquee scrollamount=\"15\" direction=\"left\"  marquee width=25% marquee height=100%>\r\n");
      out.write("\t<img src=\"images/race.jpg\"/>\r\n");
      out.write("\t<img src=\"images/race.jpg\"/>\r\n");
      out.write("\t<img src=\"images/race.jpg\"/>\r\n");
      out.write("\t<img src=\"images/race.jpg\"/>\r\n");
      out.write("</marquee>\r\n");
      out.write("<marquee scrollamount=\"15\" direction=\"left\"  marquee width=25% marquee height=100%>\r\n");
      out.write("\t<img src=\"images/race.jpg\"/>\r\n");
      out.write("\t<img src=\"images/race.jpg\"/>\r\n");
      out.write("\t<img src=\"images/race.jpg\"/>\r\n");
      out.write("\t<img src=\"images/race.jpg\"/>\r\n");
      out.write("</marquee>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"jumbotron \" style=\"margin-top: -35px\">\r\n");
      out.write("<h2><marquee bgcolor=\"#66CD00\" scrollamount=\"9\" width=9% >&lt;&lt;&lt;</marquee>\r\n");
      out.write("<strong>FRANCHISEE MANAGEMENT SYSTEM</strong>\r\n");
      out.write("<marquee bgcolor=\"#66CD00\" scrollamount=\"9\" direction=\"right\" width=9%>&gt;&gt;&gt;</marquee></h2>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<marquee scrollamount=\"15\" direction=\"up\"  marquee width=24% marquee height=100%>\r\n");
      out.write("<img src=\"images/race.jpg\"/>\r\n");
      out.write("</marquee>\t\r\n");
      out.write("<marquee scrollamount=\"15\" direction=\"left\"  marquee width=25% marquee height=100%>\r\n");
      out.write("\t<img src=\"images/race.jpg\"/>\r\n");
      out.write("\t<img src=\"images/race.jpg\"/>\r\n");
      out.write("\t<img src=\"images/race.jpg\"/>\r\n");
      out.write("\t<img src=\"images/race.jpg\"/>\r\n");
      out.write("</marquee>\r\n");
      out.write("<marquee scrollamount=\"15\" direction=\"left\"  marquee width=25% marquee height=100%>\r\n");
      out.write("\t<img src=\"images/race.jpg\"/>\r\n");
      out.write("\t<img src=\"images/race.jpg\"/>\r\n");
      out.write("\t<img src=\"images/race.jpg\"/>\r\n");
      out.write("\t<img src=\"images/race.jpg\"/>\r\n");
      out.write("</marquee>\r\n");
      out.write("<marquee scrollamount=\"15\" direction=\"left\"  marquee width=25% marquee height=100%>\r\n");
      out.write("\t<img src=\"images/race.jpg\"/>\r\n");
      out.write("\t<img src=\"images/race.jpg\"/>\r\n");
      out.write("\t<img src=\"images/race.jpg\"/>\r\n");
      out.write("\t<img src=\"images/race.jpg\"/>\r\n");
      out.write("</marquee>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- <div class=\"w3-content\" style=\"max-width:1200px\">\r\n");
      out.write(" \r\n");
      out.write("  <div class=\"w3-row-padding w3-section\">\r\n");
      out.write("    <div class=\"col-sm-3 col-xs-12\">\r\n");
      out.write("      <img class=\"demo w3-opacity w3-hover-opacity-on\" src=\"images/bmw.jpg\" style=width:115%;height:400px;margin-left:23px >\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"col-sm-3 col-xs-12\">\r\n");
      out.write("      <img class=\"demo w3-opacity w3-hover-opacity-off\" src=\"images/truck.jpg\" style=\"width:115%;height:400px;margin-right:-100px;float:right\" >\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"col-sm-3 col-xs-12\">\r\n");
      out.write("      <img class=\"demo w3-opacity w3-hover-opacity-off\" src=\"images/honda1.jpg\" style=\"width:115%;height:400px;margin-right:-130px;float:right\" >\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    <div class=\"col-sm-3 col-xs-12\">\r\n");
      out.write("      <img class=\"demo w3-opacity w3-hover-opacity-off\" src=\"images/car2.jpg\" style=\"width:115%;height:400px;margin-left:43px;margin-right:-160px;float:right\" >\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</div> -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write("\r\n");
      out.write("<!-- Container (Register Section) -->\r\n");
      out.write("<div  id=\"Register\" class=\"container-fluid\"   >\r\n");
      out.write("  <div class=\"text-center\"><br><br><br>\r\n");
      out.write("<h2><marquee scrollamount=\"9\" width=9% >&lt;&lt;&lt;</marquee>\r\n");
      out.write("<strong>REGISTRATION PORTAL</strong>\r\n");
      out.write("<marquee  scrollamount=\"9\" direction=\"right\" width=9%>&gt;&gt;&gt;</marquee>\r\n");
      out.write("</h2>\r\n");
      out.write("    <h4>Please Choose a registration plan that works for you</h4>\r\n");
      out.write("  </div>\r\n");
      out.write("  \r\n");
      out.write("    <div class=\"col-sm-6 col-xs-12\">\r\n");
      out.write("      <div class=\"panel panel-default text-center\">\r\n");
      out.write("        <div class=\"panel-heading\">\r\n");
      out.write("          <h1>Franchisor Sign-up</h1>\r\n");
      out.write("        </div>\r\n");
      out.write("       \r\n");
      out.write("        <div class=\"panel-footer\">\r\n");
      out.write("          <h3> </h3><br>\r\n");
      out.write("          <h4> </h4><br>\r\n");
      out.write("            <a href=\"frreg.jsp\">\r\n");
      out.write("      \t    <button class=\"btn btn-primary btn-lg btn-block\">Sign-up</button></a>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>      \r\n");
      out.write("    </div>     \r\n");
      out.write("    <div class=\"col-sm-6 col-xs-12\">\r\n");
      out.write("      <div class=\"panel panel-primary text-center\">\r\n");
      out.write("        <div class=\"panel-heading\">\r\n");
      out.write("          <h1>Franchisee Sign-up</h1>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        <div class=\"panel-footer\">\r\n");
      out.write("          <h3> </h3><br>\r\n");
      out.write("          <h4> </h4><br>\r\n");
      out.write("          <a href=\"fereg.jsp\">\r\n");
      out.write("      \t   <button class=\"btn btn-primary btn-lg btn-block\">Sign-up</button></a>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>      \r\n");
      out.write("    </div>       \r\n");
      out.write("    \r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Container (About Section) -->\r\n");
      out.write("<div id=\"about\" class=\"container-fluid\">\r\n");
      out.write("  <div class=\"row\">\r\n");
      out.write("    <div class=\"col-sm-7\">\r\n");
      out.write("      <h2><br> <br> <br>About Company Page</h2><br>\r\n");
      out.write("      <p>Franchise Management Platform (FMP)TM is a\r\n");
      out.write("\t\t\t\t\thighly customizable, Open Source-based franchise management system\r\n");
      out.write("\t\t\t\t\tdelivered on a hosted, managed, configured and fully supported\r\n");
      out.write("\t\t\t\t\tsolution stack for managing relationships, content, operations and\r\n");
      out.write("\t\t\t\t\tperformance among franchise owners (franchisors), franchisees and\r\n");
      out.write("\t\t\t\t\tcustomers.</p>\r\n");
      out.write("\t <p>Our innovative franchise management software enables the franchiser\r\n");
      out.write("\t\t\t\t\tto imbibe its corporate culture into consistent franchisee service,\r\n");
      out.write("\t\t\t\t\twhich drives better employee engagement, leading to improved\r\n");
      out.write("\t\t\t\t\tcustomer experience.</p>\t\r\n");
      out.write("\t\t<p>FMP comprises the following building blocks to enable a 360' view of the franchisor-franchisee world</p>\r\n");
      out.write("\t\t<p> * Owner relationship management</p>\r\n");
      out.write("\t\t<p> * Franchise content management</p>\r\n");
      out.write("\t\t<p> * Operations and performance management</p>\r\n");
      out.write("\t\t<p> * Deal management</p>\r\n");
      out.write("\t\t<p> * Contract management</p>\t\t\t\r\n");
      out.write("\t\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"col-sm-5\" >\r\n");
      out.write("    <a ><br> <br> <br><br> <br> <br><img src=\"images/about.JPG\" alt=\"Franchisee Management System\" title=\"Franchisee Management System\"></a>\r\n");
      out.write("      \r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"container-fluid bg-grey\">\r\n");
      out.write("  <div class=\"row\">\r\n");
      out.write("    \r\n");
      out.write("    <div class=\"col-sm-8\">\r\n");
      out.write("      <h2>Features</h2><br>\r\n");
      out.write("      <h4>Franchisor : </h4><p><strong>* Visibility  - </strong>Franchise software enabling 360 degree view of franchisees and their performance</p>\r\n");
      out.write("      <p><strong> * Operation Management  -</strong>  Streamlined processes to manage franchisee agreements, enable new store concepts, new franchisee approval, lead management and more.</p>\r\n");
      out.write("\t  <p><strong> * Collaboration  -  </strong>Collaboration with franchisees over social platform - team rooms, wikis, forums and blogs</p>\r\n");
      out.write("\t  <p><strong> * Franchise marketing  -  </strong>Brands standard messaging with broadcast capabilities to simultaneously communicate new product launches, training and marketing campaigns to all franchisees</p>\r\n");
      out.write("      \r\n");
      out.write("      <h4>Franchisee : </h4><p><strong>* Registration  -  </strong>No hassles on-boarding, operating policies and procedures, quality, safety and reporting Metrics</p>\r\n");
      out.write("      <p><strong> *  Self-learning - </strong> Access to Knowledgebase, smart FAQ, franchise improvement collaboration, Gamification</p>\r\n");
      out.write("\t  <p><strong> * Fast retrieval of information - </strong>Parametric search, multilingual content</p>\r\n");
      out.write("\t  <p><strong> * Role-based access - </strong>Owner service, e-Concierge</p>\r\n");
      out.write("\t  <p><strong> * Profitable tools - </strong>Daily deal socialization and e-Coupons</p>\r\n");
      out.write("\t    </div>\r\n");
      out.write("\t    <div>\r\n");
      out.write("\t    <h2>Benefits</h2><br>\r\n");
      out.write("\t   <p> * Enhanced productivity and performance through relevant information, processes tracking and automated workflow</p>\r\n");
      out.write("<p> * Easy to use, mobile-ready</p>\r\n");
      out.write("<p> * Franchise management software relevant to corporate culture</p>\r\n");
      out.write("<p> * No lock-in with micro-vendor</p>\r\n");
      out.write("<p> * Available as on-premise and SaaS models</p>\r\n");
      out.write("<p> * Ready to run in 60 days</p>\r\n");
      out.write("\t    </div>\r\n");
      out.write("\t    <div class=\"col-sm-4\">\r\n");
      out.write("      <span class=\"glyphicon glyphicon-signal logo slideanim\"></span>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Container (Contact Section) -->\r\n");
      out.write("<div id=\"contact\" class=\"container-fluid bg-grey\">\r\n");
      out.write("  <h2 class=\"text-center\"><br> <br> <br>CONTACT</h2>\r\n");
      out.write("  <div class=\"row\">\r\n");
      out.write("    <div class=\"col-sm-5\">\r\n");
      out.write("      <p>Contact us and we'll get back to you within 24 hours.</p>\r\n");
      out.write("      <p><span class=\"glyphicon glyphicon-map-marker\"></span> MANIT-BHOPAL, INDIA</p>\r\n");
      out.write("      <p><span class=\"glyphicon glyphicon-phone\"></span> +91 9455227345 , +91 7376513932</p>\r\n");
      out.write("      <p><span class=\"glyphicon glyphicon-envelope\"></span> kpajay.17@gmail.com</p>\r\n");
      out.write("    </div>\r\n");
      out.write("   \r\n");
      out.write("    <div class=\"col-sm-7 slideanim\">\r\n");
      out.write("     <form action=\"comments.jsp\" method=\"post\">\r\n");
      out.write("      <div class=\"row\">\r\n");
      out.write("        <div class=\"col-sm-6 form-group\">\r\n");
      out.write("          <input class=\"form-control\" id=\"name\" name=\"name\" placeholder=\"Name\" type=\"text\" required>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"col-sm-6 form-group\">\r\n");
      out.write("          <input class=\"form-control\" id=\"email\" name=\"email\" placeholder=\"Email\" type=\"email\" required>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <textarea class=\"form-control\" id=\"comments\" name=\"comments\" placeholder=\"Comment(Maximum 300 Character)\" rows=\"5\"></textarea><br>\r\n");
      out.write("      <div class=\"row\">\r\n");
      out.write("        <div class=\"col-sm-12 form-group\">\r\n");
      out.write("        <input type=\"submit\" class=\"btn btn-default pull-right\" value=\"Send\" maxlength=\"300\"  name=\"login\">\r\n");
      out.write("         \r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      </form>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div><br><br><br><br><br>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- Add Google Maps -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("       \r\n");
      out.write(" ");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
