/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.73
 * Generated at: 2017-09-13 14:48:57 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("body p,h1,h2,h3,h4,h5,h6,a{\r\n");
      out.write("\tfont-size: 30px;\r\n");
      out.write("      text-transform: uppercase;\r\n");
      out.write("      color: red;\r\n");
      out.write("      font-weight: 600;\r\n");
      out.write("      margin-bottom: 30px;\r\n");
      out.write("      font-family: Segoe Print, serif;\r\n");
      out.write("}\r\n");
      out.write("body {/*--\r\n");
      out.write("\tbackground:pink;\r\n");
      out.write("\t*/\r\n");
      out.write("    background: url(\"images/Bugatti.jpg\") no-repeat 62% 34%;\r\n");
      out.write("    background-size: cover;\r\n");
      out.write("\ttext-align:center;\r\n");
      out.write("}\r\n");
      out.write("/*--header--*/\r\n");
      out.write(".agileheader h1 {\r\n");
      out.write("    font-size: 51px;\r\n");
      out.write("    text-transform: uppercase;\r\n");
      out.write("    letter-spacing: 5px;\r\n");
      out.write("    color: #fff;\r\n");
      out.write("    font-weight: 400;\r\n");
      out.write("    margin: 20px 0px;\r\n");
      out.write("}\r\n");
      out.write(".ajay-main h2 {\r\n");
      out.write("\tcolor: #fff;\r\n");
      out.write("    font-size: 29px;\r\n");
      out.write("    letter-spacing: 2px;\r\n");
      out.write("    text-transform: uppercase;\r\n");
      out.write("    padding-bottom: 15px;\r\n");
      out.write("}\r\n");
      out.write(".ajay-main {   \r\n");
      out.write("    width: 45%;\r\n");
      out.write("    margin: 0 auto;\r\n");
      out.write("    background:rgba(0, 0, 0, 0.3);\r\n");
      out.write("    padding: 42px 35px;\r\n");
      out.write("}\r\n");
      out.write("/*--//header--*/\r\n");
      out.write("/*--main--*/\r\n");
      out.write("input[type=\"text\"], input[type=\"password\"],select[type=\"dropdown\"]{\r\n");
      out.write("    width: 40%;\r\n");
      out.write("    padding: 15px 0px 15px 42px;\r\n");
      out.write("    border: 1px solid #fff;\r\n");
      out.write("    outline: none;\r\n");
      out.write("    font-size: 18px;\r\n");
      out.write("    color: #fff;\r\n");
      out.write("    margin: 14px 3px;\r\n");
      out.write("    font-family: 'Roboto', sans-serif;\r\n");
      out.write("}\r\n");
      out.write("select[type=\"dropdown\"] {\r\n");
      out.write("    background: url(\"images/person.png\") no-repeat 10px 11px;\r\n");
      out.write("    background-size: 23px;\r\n");
      out.write("   background:rgba(0, 0, 0, 0.3);\r\n");
      out.write("    width:40%;\r\n");
      out.write("    \r\n");
      out.write("}\r\n");
      out.write("input[type=\"text\"] {\r\n");
      out.write("    background: url(\"images/person.png\") no-repeat 10px 11px;\r\n");
      out.write("    background-size: 24px;\r\n");
      out.write("}\r\n");
      out.write("input[type=\"password\"] {\r\n");
      out.write("    background: url(\"images/pass.png\") no-repeat 8px 9px;\r\n");
      out.write("    background-size: 28px;\r\n");
      out.write("}\r\n");
      out.write(".ajay-main span {\r\n");
      out.write("//font-weight: 600;\r\n");
      out.write("      font-style: ;\r\n");
      out.write("      //text-decoration:underline;\r\n");
      out.write("    font-size: 16px;\r\n");
      out.write("    color: #fff;\r\n");
      out.write("    float: left;\r\n");
      out.write("    width: 52%;\r\n");
      out.write("\tmargin-top: 8px;\r\n");
      out.write("\tfont-family: 'Roboto', sans-serif;\r\n");
      out.write("}\r\n");
      out.write(".ajay-main h6 {\r\n");
      out.write("    font-size: 16px;\r\n");
      out.write("    float: right;\r\n");
      out.write("    width: 37%;\r\n");
      out.write("\tcolor: #fff;\r\n");
      out.write("    letter-spacing: 1px;\r\n");
      out.write("\tmargin-top: 8px;\r\n");
      out.write("\ttext-decoration:underline;\r\n");
      out.write("}\r\n");
      out.write(".ajay-main a {\r\n");
      out.write("    color: #fff;\r\n");
      out.write("\ttransition:0.5s all;\r\n");
      out.write("\t-webkit-transition:0.5s all;\r\n");
      out.write("\t-o-transition:0.5s all;\r\n");
      out.write("\t-moz-transition:0.5s all;\r\n");
      out.write("\t-ms-transition:0.5s all;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("input[type=\"submit\"] {\r\n");
      out.write("    padding: 12px 38px;\r\n");
      out.write("    font-size: 18px;\r\n");
      out.write("    text-transform: uppercase;\r\n");
      out.write("    letter-spacing: 2px;\r\n");
      out.write("    background: #003b64;\r\n");
      out.write("    color: white;\r\n");
      out.write("    border: none;\r\n");
      out.write("    outline: none;\r\n");
      out.write("    cursor: pointer;\r\n");
      out.write("    font-family: 'Roboto', sans-serif;\r\n");
      out.write("    margin: 45px auto 31px;\r\n");
      out.write("    transition: 0.5s all;\r\n");
      out.write("   \r\n");
      out.write("}\r\n");
      out.write("input[type=\"submit\"]:hover {\r\n");
      out.write("\tbackground:rgba(213, 38, 133, 0.64);\r\n");
      out.write("\ttransition:0.5s all;\r\n");
      out.write("\t-webkit-transition:0.5s all;\r\n");
      out.write("\t-o-transition:0.5s all;\r\n");
      out.write("\t-moz-transition:0.5s all;\r\n");
      out.write("\t-ms-transition:0.5s all;\r\n");
      out.write("}\r\n");
      out.write(".ajay-main p a {\r\n");
      out.write("    text-transform: uppercase;\r\n");
      out.write("    font-size: 18px;\r\n");
      out.write("\ttext-decoration:underline;\r\n");
      out.write("    letter-spacing: 1px;\r\n");
      out.write("    color: #fff;\r\n");
      out.write("    padding: 10px;\r\n");
      out.write("}\r\n");
      out.write(".ajay-main p {\r\n");
      out.write("    font-size: 17px;\r\n");
      out.write("    color: #fff;\r\n");
      out.write("}\r\n");
      out.write("/*--//main--*/\r\n");
      out.write("\r\n");
      out.write("/*--footer--*/\r\n");
      out.write(".footer-w3l p {\r\n");
      out.write("    margin: 4em 0em;\r\n");
      out.write("    color: #fff;\r\n");
      out.write("    font-size: 15px;\r\n");
      out.write("    font-weight: 300;\r\n");
      out.write("    letter-spacing: 2px;\r\n");
      out.write("}\r\n");
      out.write(".footer-w3l a {\r\n");
      out.write("    color:rgba(208, 95, 216, 0.9);\r\n");
      out.write("}\r\n");
      out.write(".footer-w3l a:hover {\r\n");
      out.write("    color:rgba(19, 129, 206, 0.82);;\r\n");
      out.write("    text-decoration: underline;\r\n");
      out.write("}\r\n");
      out.write("/*--//footer--*/\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<!--header-->\r\n");
      out.write("<div class=\"agileheader\">\r\n");
      out.write("\t<h1></h1>\r\n");
      out.write("</div>\r\n");
      out.write("<!--//header-->\r\n");
      out.write("\r\n");
      out.write("<!--main-->\r\n");
      out.write("<div class=\"main-w3l\">\r\n");
      out.write("<div class=\"ajay-main\">\r\n");
      out.write("\t<h3 bgcolor=\"red\"><marquee scrollamount=\"5\" width=\"70\" >&lt;&lt;&lt;</marquee>LogIn Page<marquee scrollamount=\"5\" direction=\"right\" width=\"70\">&gt;&gt;&gt;</marquee></h3>\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t\t<form action=\"loginprocess.jsp\" method=\"post\">\r\n");
      out.write("\t\t\t<label style=color:white>SELECT USER  :</label>\r\n");
      out.write("\t\t\t<select value=\"user\" name=\"user\" type=\"dropdown\" required=\"required\">\r\n");
      out.write("                        \r\n");
      out.write("                        <option value=\"FRANCHISORS\" name=\"FRANCHISORS\">FRANCHISORS</option>\r\n");
      out.write("                        <option value=\"FRANCHISEES\" name=\"FRANCHISEES\">FRANCHISEES</option>\r\n");
      out.write("            </select>\r\n");
      out.write("            <br>\r\n");
      out.write("           <label style=color:white>USERNAME  : </label>  <input type=\"text\" name=\"username\" required=\"required\"/> <br>\r\n");
      out.write("\t\t   <label style=color:white>PASSWORD  : </label><input  type=\"password\" name=\"passwd\" required=\"required\"/> <br>\r\n");
      out.write("\t\t   \r\n");
      out.write("\t\t\t");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"clear\"></div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<input type=\"submit\" value=\"login\" name=\"login\"><br>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("<!--//main-->\r\n");
      out.write("<div class=\"footer-w3l\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<p>Don't Have an Account ?<a href=\"index.jsp#Register\"><strong>Register Now</strong></a></p>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("<!--footer-->\r\n");
      out.write("<div class=\"footer-w3l\">\r\n");
      out.write("\t<p>&copy; 2017 Smart Login Form. All rights reserved | Design by <a href=\"https://www.linkedin.com\">ajay</a></p>\r\n");
      out.write("</div>\r\n");
      out.write("<!--//footer-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
