/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.73
 * Generated at: 2017-09-13 14:50:54 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;

public final class loginprocess_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!DOCTYPE script PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html5/loose.dtd\">\r\n");
      out.write("    <html lang=\"en\">\r\n");
      out.write("  <html>\r\n");
      out.write(" <head>\r\n");
      out.write("  <meta charset=\"utf-8\">\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write(" <link rel=\"stylesheet\" href=\"bootstrap/css/bootstrap.min.css\">\r\n");
      out.write("  \r\n");
      out.write(" ");


 	
Connection con=null;
Statement st=null;;
ResultSet rs=null;
String sql=null;
String user = request.getParameter("user");

String username = request.getParameter("username");

String passwd = request.getParameter("passwd");


try
{
	if(user.equalsIgnoreCase("FRANCHISORS"))
		sql="select franchisorsID,username,passwd,companyname,firstname  from franchisors where username='"+username+"' and passwd='"+passwd+"' ";
	else if(user.equalsIgnoreCase("FRANCHISEES"))
		sql="select franchiseesID,username,passwd,companyname,firstname from franchisees where username='"+username+"' and passwd='"+passwd+"' ";
	Class.forName("com.mysql.jdbc.Driver");
	con = DriverManager.getConnection("jdbc:mysql://localhost/db","root","xxx");
    st = con.createStatement();
    
    rs = st.executeQuery(sql);
    if(rs.next()) {
    	if(username.equals(rs.getString(2)) && passwd.equals(rs.getString(3)))
    	{
        session.setAttribute("username", username);
        session.setAttribute("user", user);
        session.setAttribute("passwd", passwd);
        session.setAttribute("companyname",rs.getString(4));
        session.setAttribute("firstname",rs.getString(5));
        session.setAttribute("franchisorsid", rs.getString(1));
        session.setAttribute("franchiseesid", rs.getString(1));
        //  out.println("welcome " + username);
        //out.println("<a href='logout.jsp'>Log out</a>");
       //response.sendRedirect("loginprocess.jsp");
       // break;
       //out.println(rs.getString(1)+" "+rs.getString(2));
 
      out.write("\r\n");
      out.write(" <style type=\"text/css\">\r\n");
      out.write("  body {\r\n");
      out.write("         font: 400 15px Lato, sans-serif;\r\n");
      out.write("      line-height: 1.8;\r\n");
      out.write("      color: #818181;\r\n");
      out.write("  }\r\n");
      out.write("   .navbar {\r\n");
      out.write("      margin-bottom: 0;\r\n");
      out.write("      background-color:transparent ;\r\n");
      out.write("      z-index: 9999;\r\n");
      out.write("      border: 0;\r\n");
      out.write("      font-size: 20px !important;\r\n");
      out.write("      line-height: 2 !important;\r\n");
      out.write("      letter-spacing: 3px;\r\n");
      out.write("      border-radius: 0;\r\n");
      out.write("      font-family: arial, serif;\r\n");
      out.write("  }\r\n");
      out.write(" .navbar li a, .navbar .navbar-brand {\r\n");
      out.write("      color: white !important;\r\n");
      out.write("  }\r\n");
      out.write("  .navbar-nav li a:hover, .navbar-nav li.active a {\r\n");
      out.write("      color: #f4511e !important;\r\n");
      out.write("      background-color: green !important;\r\n");
      out.write("  }\r\n");
      out.write("  .navbar-default .navbar-toggle {\r\n");
      out.write("      border-color: transparent;\r\n");
      out.write("      color: #fff !important;\r\n");
      out.write("  }  \r\n");
      out.write("  .jumbotron {\r\n");
      out.write("      \r\n");
      out.write("      background: url(\"images/FlowerBackground.png\") ;\r\n");
      out.write("      color: #fff;\r\n");
      out.write("      padding: 100px 95px;\r\n");
      out.write("      font-family: Montserrat, sans-serif;\r\n");
      out.write("       width: 100%;\r\n");
      out.write("     height: 150px;\r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("  }\r\n");
      out.write(" </style>\r\n");
      out.write(" <title style=text-transform:capitalize>");
out.println(rs.getString(5)+"..."+rs.getString(4));
      out.write("</title>\r\n");
      out.write(" </head>\r\n");
      out.write("<body>\r\n");
      out.write("<div  class=\"jumbotron text-center\">\r\n");
      out.write("<div class=\"navbar navbar-default\">\r\n");
      out.write("  <div class=\"container\">\r\n");
      out.write("    <div class=\"navbar-header\">\r\n");
      out.write("    \r\n");
      out.write("     <span style=font-size:22px;text-transform:uppercase;margin-top:-25px > ");
out.println(rs.getString(4));
      out.write("</span><br>\r\n");
      out.write("    \r\n");
      out.write("      <button type=\"button\" class=\"navbar-toggle\" data-toggle=\"collapse\" data-target=\"#myNavbar\">\r\n");
      out.write("        <span class=\"icon-bar\"></span>\r\n");
      out.write("        <span class=\"icon-bar\"></span>\r\n");
      out.write("        <span class=\"icon-bar\"></span>                        \r\n");
      out.write("      </button>\r\n");
      out.write("      \r\n");
      out.write("     \r\n");
      out.write("     <span class=\"glyphicon glyphicon-user\" style=font-size:44px;text-transform:capitalize> \r\n");
      out.write("    ");
out.println(rs.getString(5));
      out.write("\r\n");
      out.write("     </span><br>\r\n");
      out.write("    </div><br>\r\n");
      out.write("    <div class=\"collapse navbar-collapse\" id=\"myNavbar\">\r\n");
      out.write("      <ul class=\"nav navbar-nav navbar-right\">\r\n");
      out.write("       <li><a href=\"product.jsp\">\r\n");
      out.write("      \t\t<span class=\"glyphicon glyphicon-list-alt\" ></span>Product</a></li>\r\n");
      out.write("      \t\t\r\n");
      out.write("      \t\t <li><a href=\"order.jsp\">\r\n");
      out.write("      \t\t<span class=\"glyphicon glyphicon-log-in\"></span>Order</a></li>\r\n");
      out.write("      \t\t");
if(user.equalsIgnoreCase("FRANCHISORS"))
      			{
      out.write("\r\n");
      out.write("      <li><a href=\"franchiseelist.jsp\">\r\n");
      out.write("            <span class=\"glyphicon glyphicon-user\"></span>Franchisee</a></li>\r\n");
      out.write("            ");
} 
      out.write("\r\n");
      out.write("     <li><a href=\"logout.jsp\" >\r\n");
      out.write("   <span class=\"glyphicon glyphicon-log-out\"></span>logout</a></li>\r\n");
      out.write("      </ul>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"row\">\r\n");
      out.write("<div class=\"w3-content\" style=\"max-width:1200px\">\r\n");
      out.write("  \r\n");
      out.write("  <div class=\"w3-row-padding w3-section\">\r\n");
      out.write("    <div class=\"col-sm-5 col-xs-12\">\r\n");
      out.write("      <img class=\"demo w3-opacity w3-hover-opacity-on\" src=\"images/race.jpg\" style=width:115%;height:400px;margin-left:23px >\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"col-sm-4 col-xs-12\">\r\n");
      out.write("      <img class=\"demo w3-opacity w3-hover-opacity-off\" src=\"images/race2.jpg\" style=\"width:115%;height:400px;margin-right:-100px;float:right\" >\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"col-sm-3 col-xs-12\">\r\n");
      out.write("      <img class=\"demo w3-opacity w3-hover-opacity-off\" src=\"images/race3.jpg\" style=\"width:115%;height:400px;margin-right:-130px;float:right\" >\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("    ");

    	}
    }else {
    	
      out.write("\r\n");
      out.write("    \t<script>\r\n");
      out.write("    \talert(\"Invalid password !!! \\n Please Enter Valid Password\");\r\n");
      out.write("    \twindow.location = 'login.jsp';\r\n");
      out.write("    \t</script>\r\n");
      out.write("    \t");
 
//out.print("alert('Password expired, please update your password..');");
      //out.println("Invalid password <a href='login.jsp'>try again</a>");
//response.sendRedirect("login.jsp");
    }
con.close();

}catch(Exception e)
{
	
      out.write("\r\n");
      out.write("\t<script>\r\n");
      out.write("\talert(\"Error Please Try Again\");\r\n");
      out.write("    </script>\r\n");
      out.write("    \r\n");
      out.write("    ");

    response.sendRedirect("login.jsp");
	
}


      out.write("\r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
