/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.73
 * Generated at: 2017-09-13 17:41:50 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import java.sql.Connection;

public final class product_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {


Connection con=null;
PreparedStatement pst=null;
ResultSet rs=null;
String sql=null;


  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;


    if ((session.getAttribute("username") == null) || (session.getAttribute("passwd") == "")) {
    	response.sendRedirect("login.jsp");
    }else
    {

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("  <head>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->\r\n");
      out.write("    <meta name=\"description\" content=\"\">\r\n");
      out.write("    <meta name=\"author\" content=\"\">\r\n");
      out.write("    <title>Product</title>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"bootstrap/css/bootstrap.min.css\">\r\n");
      out.write("  <script  src=\"bootstrap/css/bootstrap.min.css\"></script>\r\n");
      out.write("  <script  src=\"js/3.1.1/jquery.min.js\"></script>\r\n");
      out.write("  <script  src=\"bootstrap/js/bootstrap.js\"></script>\r\n");
      out.write("  <script src=\"bootstrap/js/bootstrap.min.js\"></script>\r\n");
      out.write("     <style>\r\n");
      out.write("    /* Remove the navbar's default margin-bottom and rounded borders */ \r\n");
      out.write("    .navbar {\r\n");
      out.write("      margin-bottom: 0;\r\n");
      out.write("      border-radius: 0;\r\n");
      out.write("      height:110px;\r\n");
      out.write("    }\r\n");
      out.write("   * {font-family: Helvetica Neue, Arial, sans-serif; }\r\n");
      out.write("\r\n");
      out.write("body { background: url(\"images/bg3.jpg\");}\r\n");
      out.write("\r\n");
      out.write("h1, table { text-align: center; }\r\n");
      out.write("\r\n");
      out.write("table {border-collapse: collapse;  width: 95%; margin: 0 auto .5rem;}\r\n");
      out.write("\r\n");
      out.write("th, td { padding: 1rem; font-size: 2rem;color: }\r\n");
      out.write("\r\n");
      out.write("tr {background: hsl(50, 50%, 80%); }\r\n");
      out.write("\r\n");
      out.write(" td { transition: .4s ease-in;text-align: center; } \r\n");
      out.write("\r\n");
      out.write("tr:first-child {background: hsla(12, 100%, 40%, 0.5); }\r\n");
      out.write("\r\n");
      out.write("tr:nth-child(even) { background: hsla(50, 50%, 80%, 0.7); }\r\n");
      out.write("\r\n");
      out.write("td:empty {background: hsla(50, 25%, 60%, 0.7); }\r\n");
      out.write("\r\n");
      out.write("tr:hover:not(#firstrow), tr:hover td:empty {background: #ff0; pointer-events: visible;}\r\n");
      out.write("tr:hover:not(#firstrow) { transform: scale(1.01); font-weight: 700; box-shadow: 0px 3px 1px rgba(0, 0, 0, 0.5);}\r\n");
      out.write("  .jumbotron {\r\n");
      out.write("      \r\n");
      out.write("      background: url(\"images/FlowerBackground.png\") ;\r\n");
      out.write("      color: #fff;\r\n");
      out.write("      padding: 100px 95px;\r\n");
      out.write("      font-family: Montserrat, sans-serif;\r\n");
      out.write("       width: 100%;\r\n");
      out.write("     height: 150px;\r\n");
      out.write("     }\r\n");
      out.write("     .navbar {\r\n");
      out.write("      margin-bottom: 0;\r\n");
      out.write("      background-color:transparent ;\r\n");
      out.write("      z-index: 9999;\r\n");
      out.write("      border: 0;\r\n");
      out.write("      font-size: 20px !important;\r\n");
      out.write("      line-height: 2 !important;\r\n");
      out.write("      letter-spacing: 3px;\r\n");
      out.write("      border-radius: 0;\r\n");
      out.write("      font-family: arial, serif;\r\n");
      out.write("  }\r\n");
      out.write("     .navbar li a, .navbar .navbar-brand {\r\n");
      out.write("      color: white !important;\r\n");
      out.write("  }\r\n");
      out.write("  .navbar-nav li a:hover, .navbar-nav li.active a {\r\n");
      out.write("      color: pink !important;\r\n");
      out.write("      background-color: green !important;\r\n");
      out.write("  }\r\n");
      out.write("     .navbar-default .navbar-toggle {\r\n");
      out.write("      border-color: transparent;\r\n");
      out.write("      color: #fff !important;\r\n");
      out.write("  }  \r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write(" \r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<div  class=\"jumbotron text-center\">\r\n");
      out.write(" <div class=\"navbar navbar-default\">\r\n");
      out.write("  <div class=\"container\">\r\n");
      out.write("    <div class=\"navbar-header\">\r\n");
      out.write("   ");
 String companyname=(String)session.getAttribute("companyname");
      out.write("\r\n");
      out.write("      \r\n");
      out.write("    \r\n");
      out.write("      <button type=\"button\" class=\"navbar-toggle\" data-toggle=\"collapse\" data-target=\"#myNavbar\">\r\n");
      out.write("        <span class=\"icon-bar\"></span>\r\n");
      out.write("        <span class=\"icon-bar\"></span>\r\n");
      out.write("        <span class=\"icon-bar\"></span>  \r\n");
      out.write("                             \r\n");
      out.write("      </button>\r\n");
      out.write("       <span style=font-size:22px;text-transform:uppercase;margin-top:-25px > \r\n");
      out.write("       ");
out.println(companyname);
      out.write("</span><br>\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    ");
 String uname=(String)session.getAttribute("username");
    String user=(String)session.getAttribute("user");
    String firstname=(String)session.getAttribute("firstname");
      out.write("\r\n");
      out.write("     <span class=\"glyphicon glyphicon-user\" style=font-size:44px;text-transform:capitalize> \r\n");
      out.write("     ");
out.println(firstname);
      out.write("</span><br>\r\n");
      out.write("    </div><br>\r\n");
      out.write("    <div class=\"collapse navbar-collapse\" id=\"myNavbar\">\r\n");
      out.write("      <ul class=\"nav navbar-nav navbar-right\">\r\n");
      out.write("       <li><a href=\"product.jsp\">\r\n");
      out.write("      \t\t<span class=\"glyphicon glyphicon-list-alt\"></span>Product</a></li>\r\n");
      out.write("      \t\t <li><a href=\"order.jsp\">\r\n");
      out.write("      \t\t<span class=\"glyphicon glyphicon-log-in\"></span>Order</a></li>\r\n");
      out.write("      ");
if(user.equalsIgnoreCase("FRANCHISORS"))
      			{
      out.write("\r\n");
      out.write("      <li><a href=\"franchiseelist.jsp\">\r\n");
      out.write("            <span class=\"glyphicon glyphicon-user\"></span>Franchisee</a></li>\r\n");
      out.write("            ");
} 
      out.write("  \r\n");
      out.write("      <li><a href=\"\" >\r\n");
      out.write("      \t\t<span class=\"glyphicon glyphicon-home\"></span>Home</a></li>  \r\n");
      out.write("     <li><a href=\"loginprocess.jsp\" >\r\n");
      out.write("            <span class=\"glyphicon glyphicon-log-out\"></span>logout</a></li>\r\n");
      out.write("      </ul>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"row\">\r\n");
      out.write("   <div class=\"col-lg-12\">\r\n");
      out.write("   <br>\r\n");
      out.write("   </div>\r\n");
      out.write("</div>\r\n");
      out.write("<table align=\"center\" cellpadding=\"5\" cellspacing=\"5\" border=\"1\"  >\r\n");
      out.write('\r');
      out.write('\n');

try{ 
	String s=null;
	
	
	if(user.equalsIgnoreCase("FRANCHISORS"))
	{
		sql="select * from products where franchisorsID=?";
		s=(String)session.getAttribute("franchisorsid");
	}
	else 
	{
		sql="select modelname,color,type,quantity from orderitems where ordersID in (select ordersID from orders where franchiseesID=? and status='delivered')";
		s=(String)session.getAttribute("franchiseesid");
	}
Class.forName("com.mysql.jdbc.Driver");
	con = DriverManager.getConnection("jdbc:mysql://localhost/db","root","xxx");
    pst = con.prepareStatement(sql);
    pst.setString(1,s);
   int count=1; 
    rs = pst.executeQuery();
 if(user.equalsIgnoreCase("FRANCHISORS"))
 {
      out.write("\r\n");
      out.write("    <tr bgcolor=\"#A52A2A\">\r\n");
      out.write("\r\n");
      out.write("    <td><b>S/N</b></td>\r\n");
      out.write("    <td><b>ModelName</b></td>\r\n");
      out.write("    <td><b>Color</b></td>\r\n");
      out.write("    <td><b>Type</b></td>\r\n");
      out.write("    <td><b>price</b></td>\r\n");
      out.write("    <td><b>Status</b></td>\r\n");
      out.write("    <td><b>SellingPrice</b></td>\r\n");
      out.write("    <td><b>Quantity</b></td>\r\n");
      out.write("\r\n");
      out.write("    </tr>\r\n");

while(rs.next()){

      out.write("\r\n");
      out.write("<tr bgcolor=\"#DEB887\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("      <tr><td>");
out.println(count++);
      out.write("</td>\r\n");
      out.write("      <td>");
out.println(rs.getString(1));
      out.write("</td>\r\n");
      out.write("      <td >");
out.println(rs.getString(2));
      out.write("</td>\r\n");
      out.write("      <td>");
out.println(rs.getString(3));
      out.write("</td>\r\n");
      out.write("      <td >");
out.println(rs.getString(4));
      out.write("</td>\r\n");
      out.write("      <td>");
out.println(rs.getString(5));
      out.write("</td>\r\n");
      out.write("      <td >");
out.println(rs.getString(6));
      out.write("</td>\r\n");
      out.write("      <td>");
out.println(rs.getString(8));
      out.write("</td>\r\n");
      out.write("      \r\n");
      out.write("</tr>\r\n");
      out.write("\r\n");
 
}
 }
else 
{
	
      out.write("\r\n");
      out.write("\t <tr bgcolor=\"#A52A2A\">\r\n");
      out.write("\r\n");
      out.write("\t    <td><b>S/N</b></td>\r\n");
      out.write("\t    <td><b>ModelName</b></td>\r\n");
      out.write("\t    <td><b>Color</b></td>\r\n");
      out.write("\t    <td><b>Type</b></td>\r\n");
      out.write("\t    <td><b>Quantity</b></td>\r\n");
      out.write("\t    </tr>\r\n");
      out.write("\t");

	while(rs.next()){
	
      out.write("\r\n");
      out.write("\t<tr bgcolor=\"#DEB887\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t      <tr><td>");
out.println(count++);
      out.write("</td>\r\n");
      out.write("\t      <td>");
out.println(rs.getString(1));
      out.write("</td>\r\n");
      out.write("\t      <td >");
out.println(rs.getString(2));
      out.write("</td>\r\n");
      out.write("\t      <td>");
out.println(rs.getString(3));
      out.write("</td>\r\n");
      out.write("\t      <td >");
out.println(rs.getString(4));
      out.write("</td>\r\n");
      out.write("\t      \r\n");
      out.write("\t       \r\n");
      out.write("\t</tr>\r\n");
      out.write("\t");

}
}
}
 catch (Exception e) {
e.printStackTrace();
}

      out.write("\r\n");
      out.write("</table>\r\n");
} 
      out.write('\r');
      out.write('\n');
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
